#!/usr/bin/env bash
# Создаёт метки проекта в текущем репозитории. Запуск: bash scripts/setup-labels.sh
set -euo pipefail
label() { gh label create "$1" --color "$2" --description "$3" --force; }
label "area:mobile" 1D76DB "Мобильное приложение"
label "area:api" 1D76DB "API и серверные модули, кроме синхронизации"
label "area:sync" 1D76DB "Синхронизация: клиент и сервер"
label "area:web" 1D76DB "Публичный веб"
label "area:backoffice" 1D76DB "Инструмент редактора"
label "area:content" 1D76DB "Конвейер словаря, колоды, данные"
label "area:docs" 1D76DB "Только документы"
label "type:feature" 0E8A16 "Новая функция"
label "type:bug" D93F0B "Ошибка"
label "type:content" 0E8A16 "Словарь и колоды"
label "type:chore" C5DEF5 "Инфраструктура, зависимости, CI"
label "type:owner" FEF2C0 "Задача владельца продукта, не для разработки"
label "size:S" EDEDED "До полудня"
label "size:M" EDEDED "1–2 дня"
label "size:L" EDEDED "Нужно дробить"
label "p1" B60205 "Обязательно для беты"
label "p2" FBCA04 "Желательно"
label "needs-info" D876E3 "Нужны ответы владельца"
label "needs-design" 5319E7 "Нужен план архитектора"
label "triage:done" 0E8A16 "Разбор завершён, ждёт ready"
label "ready" 0E8A16 "В работу (ставит только владелец)"
label "blocked" 000000 "Ждёт другую задачу"
label "later" CCCCCC "После беты"
label "duplicate" CCCCCC "Дубликат"
label "report" BFD4F2 "Еженедельный отчёт"
echo "Метки созданы."
